parameters: 
buildConfiguration: 'Release'
 
 steps:
 - task: DotNetCoreCLI@2
   displayName: 'Build the project - ${{ parameters.buildConfigurtaion }}'
   inputs:
   commands: 'build'
   arguments: '--no restore --configuration ${{ parameters.buildConfiguration }}'
   projects: '**/*.csproj'

   - task: DotNetCoreCLI@2
     displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
     inputs:
     commands: 'publish'
     arguments: '--no build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration}}'
     ZipAfterPublish: true